version: '3.8'
services:
  typebot-db:
    image: 'postgres:16'
    restart: always
    volumes:
      - 'typebot-db-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=typebot_db_prod
      - POSTGRES_PASSWORD=30041986@Max@
      - POSTGRES_USER=postgres
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U postgres'
      interval: 5s
      timeout: 5s
      retries: 5
  typebot-builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCOPE: builder
    depends_on:
      typebot-db:
        condition: service_healthy
    restart: always
    environment:
      - 'DATABASE_URL=postgresql://postgres:30041986@Max@@typebot-db:5432/typebot_db_prod'
      - ENCRYPTION_SECRET=p9X2mR7vK4wQ9zB2nH5tJ8xL1cC4vB3n
      - 'NEXTAUTH_URL=https://typebot.smarttbizz.com'
      - 'NEXT_PUBLIC_VIEWER_URL=https://typebot-v.smarttbizz.com'
      - ADMIN_EMAIL=contatomarcosconde@gmail.com
      - DISABLE_SIGNUP=false
      - SMTP_HOST=smtp.hostinger.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USERNAME=contato@agcmc.com.br
      - SMTP_PASSWORD=30041986Max@
      - NEXT_PUBLIC_SMTP_FROM=contato@agcmc.com.br
      - STRIPE_SECRET_KEY=insira_aqui_sua_sk_live_do_stripe
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=insira_aqui_sua_pk_live_do_stripe
      - STRIPE_WEBHOOK_SECRET=insira_aqui_o_secret_do_webhook_do_stripe
      - STRIPE_STARTER_PRICE_ID=prod_xxxx_ou_price_xxxx
      - STRIPE_PRO_PRICE_ID=prod_xxxx_ou_price_xxxx
  typebot-viewer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SCOPE: viewer
    depends_on:
      typebot-db:
        condition: service_healthy
    restart: always
    environment:
      - 'DATABASE_URL=postgresql://postgres:30041986@Max@@typebot-db:5432/typebot_db_prod'
      - ENCRYPTION_SECRET=p9X2mR7vK4wQ9zB2nH5tJ8xL1cC4vB3n
      - 'NEXTAUTH_URL=https://typebot.smarttbizz.com'
      - 'NEXT_PUBLIC_VIEWER_URL=https://typebot-v.smarttbizz.com'
